spring:
  application:
    name: URLShortenerBackend
  data:
    mongodb:
      uri: ${MONGODB_URI}

application:
  api:
    root: ${API_ROOT}
  encoder:
    sequenceStoreName: ${DB_SEQUENCE_NAME}
  frontend:
    errorPageAddress: ${FRONTEND_ERROR_PAGE}


