spring:
  application:
    name: URL Shortener backend
  data:
    mongodb:
      host: localhost
      port: 27017
      database: urlshortener

application:
  api:
    root: /api
  encoder:
    sequenceStoreName: shortUrlSequence
  frontend:
    errorPageAddress: http://localhost:4200/error


