spring:
  data:
    mongodb:
      host: ds253104.mlab.com
      port: 53104
      database: heroku_npzjdc1p
      password: udmdg63tiQ8PgDC
      username: sd298


application:
  api:
    root: /api
  encoder:
    sequenceStoreName: shortUrlSequence
  frontend:
    errorPageAddress: http://localhost:4200/error

server:
  port: $PORT
